### ISSUE TITLE
Support NewRelic PHP handler

### ISSUE THREAD

**Issue by augustohp** [augustohp/ansible-role-php#2]
There should be a `hwr_option.enable_newrelic` that would:
- Install NewRelic agent package.
- Configure NewRelic agent (with license key).
- Enable NewRelic agent as php extesion.

**Comment by hernandesbsousa** [comment]
Don't you think that is installing `NewRelic` is another role's responsability? I do agree that it'd be nice to have it setup the key and enable the php extension though.

**Comment by augustohp** [comment]
Agreed.
